image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: "6.9.0"
  pullPolicy: IfNotPresent

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: "/official(/|$)(.*)"
  pathType: ImplementationSpecific
