image:
  repository: roiko5/custom-podinfo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: "/custom(/|$)(.*)"
  pathType: ImplementationSpecific
